services:
  db:
    image: postgres:12.7
    container_name: imdb_db
    restart: always
    environment:
      POSTGRES_USER: imdb_user
      POSTGRES_PASSWORD: imdb_pass
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: